# Generated by Django 2.2.2 on 2019-06-17 16:03

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190616_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='done',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='Meal',
            field=models.CharField(default='meal name', max_length=50, validators=[store.models.validate_product_name]),
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
