# Generated by Django 2.2.2 on 2019-06-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190617_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Meal',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Price',
            new_name='price',
        ),
    ]
