# Generated by Django 2.2.2 on 2019-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190617_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.CharField(default='meal name', max_length=50),
        ),
    ]
