# Generated by Django 2.2.2 on 2019-06-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employs',
            name='password',
        ),
    ]
