# Generated by Django 2.2.2 on 2019-06-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_employs_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employs',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
