# Generated by Django 2.2.2 on 2019-06-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20190618_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Employs'),
            preserve_default=False,
        ),
    ]
