# Generated by Django 2.2.2 on 2019-06-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190618_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Meal',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
    ]
