# Generated by Django 2.2.2 on 2019-06-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190618_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Employs'),
        ),
    ]
