# Generated by Django 2.2.2 on 2019-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190618_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='firstname',
        ),
        migrations.AddField(
            model_name='order',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
