# Generated by Django 2.2.2 on 2019-06-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190618_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default='no comments yet..', max_length=500),
        ),
    ]
