# Generated by Django 2.2.2 on 2019-06-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20190619_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.CharField(default='meal name', max_length=50),
        ),
    ]
