# Generated by Django 2.2.2 on 2019-06-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20190619_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(default='no comments yet...', max_length=500),
        ),
    ]
