# Generated by Django 2.2.2 on 2019-06-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20190619_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeFirstname', models.CharField(max_length=20)),
                ('EmployeeDepartment', models.CharField(max_length=20)),
                ('Product', models.CharField(max_length=20)),
                ('Content', models.TextField(max_length=500)),
            ],
        ),
    ]
