# Generated by Django 2.2.2 on 2019-06-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='DateSent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
