# Generated by Django 2.2.2 on 2019-06-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20190620_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Employs'),
        ),
    ]
